/* Autogenerated file, do not edit! */

/* eslint-disable */

import { Noir, InputMap, CompiledCircuit, ForeignCallHandler } from "@noir-lang/noir_js"

export { ForeignCallHandler } from "@noir-lang/noir_js"

export type Field = string;


export const not_equal_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"x","type":{"kind":"field"},"visibility":"private"},{"name":"y","type":{"kind":"field"},"visibility":"private"}],"param_witnesses":{"x":[{"start":0,"end":1}],"y":[{"start":1,"end":2}]},"return_type":{"abi_type":{"kind":"boolean"},"visibility":"private"},"return_witnesses":[5]},"bytecode":"H4sIAAAAAAAA/7VUSQ7DIAwMJKl67U9slmBu+UpRyf9fUFVVqEQdbpiRkH2wzHjGoKYTazkcc4l7iRY253IwGS0+wcREHpxPGyGhJ/8yZG0mRyGmGCCisxkPH+0BJ+pe0AdUgry0HC/4aqYaWiqmJfQBJTkr5vlvF24N/nUdz+9V3VtwVn4v5/Jo8Lx4sAuSGWHmPKDvMsk+3hFzL/IeQdVy0qx3rw6Smq7Ce6mruVUj//vkPwR1AkL+BQAA"};

export async function not_equal(x: Field, y: Field, foreignCallHandler?: ForeignCallHandler): Promise<boolean> {
  const program = new Noir(not_equal_circuit);
  const args: InputMap = { x, y };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as boolean;
}
